name: Minha Primeira Linha de Montagem

on:
  push:
    branches: [main]

jobs:
  build-e-teste:
    runs-on: ubuntu-latest

    steps:
      - name: Pegar o chassi do carro
        uses: actions/checkout@v3

      - name: Estação de Build
        run: |
          echo "Construindo o projeto..."
          echo "Verificando se todas as peças se encaixam!"

      - name: Estação de Teste
        run: |
          echo "Rodando os testes automatizados..."
          echo "Verificando se a porta abre e fecha!"
 
